### ISSUE TITLE
`InternalError too much recursion` only when `GridColDef.valueGetter` is included

### ISSUE THREAD

**Issue by maacpiash** [mui-org/material-ui-x#1564]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

This is a component that I am using in my Next.js app:

```tsx
import React from 'react'
import {
  Button,
  Grid,
  makeStyles,
  TextField,
  Theme,
  Typography
} from '@material-ui/core'
import {
  DataGrid,
  GridColDef,
  GridValueGetterParams
} from '@material-ui/data-grid'
import { format } from 'date-fns-tz'
import { Client } from './models'

export interface FollowupListProps {
  client: Client
}

const useStyles = makeStyles((theme: Theme) => ({
  head: {
    backgroundColor: `${theme.palette.primary.main}`,
    color: '#ffffff'
  },
  table: {
    minWidth: 650
  },
  modal: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 800
  }
}))

export default function FollowupList({
  client
}: FollowupListProps): React.ReactElement<FollowupListProps> {
  const classes = useStyles()
  const { followupHistory: followups } = client
  const [searchText, setSearchText] = React.useState('')

  const formatter = (key: string, value: any): string => {
    const option = { timeZone: 'Australia/Sydney' }
    if (key === 'createdOn')
      return format(value as Date, 'dd/MM/yyyy hh:mm:ss', option)
    if (key === 'followupDate')
      return format(value as Date, 'dd/MM/yyyy', option)
    return value
  }

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'S.No.', width: 20 },
    {
      field: 'createdOn',
      headerName: 'Created On',
      width: 200,
      valueGetter: ({ getValue }: GridValueGetterParams) =>
        `${formatter('createdOn', getValue('createdOn'))}`
    },
    { field: 'createdBy', headerName: 'Created By', width: 120 },
    { field: 'createdFrom', headerName: 'Created From', width: 80 },
    { field: 'note', headerName: 'Note', width: 500 },
    {
      field: 'followupDate',
      headerName: 'Followup Date',
      width: 200,
      valueGetter: ({ getValue }: GridValueGetterParams) =>
        `${formatter('followupDate', getValue('followupDate'))}`
    }
  ]

  return (
    <div style={{ marginTop: '10px' }}>
      <Grid
        container
        direction="row"
        alignItems="center"
        className={classes.head}
      >
        <Grid item>
          <Typography variant="h6">Followup List</Typography>
        </Grid>
      </Grid>
      <fieldset>
        <legend>
          <Typography variant="h6" color="textSecondary">
            Followup History
          </Typography>
        </legend>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center'
          }}
        >
          <Button variant="contained" color="primary">
            Add Followup
          </Button>
        </div>
        {followups.length ? (
          <div>
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                justifyContent: 'right',
                marginBottom: '10px'
              }}
            >
              <TextField
                variant="outlined"
                label="Search"
                aria-label="Search followups"
                value={searchText}
                onChange={(e) => setSearchText(e.target.value)}
              />
            </div>
            <div style={{ height: 1000, width: '100%' }}>
              <DataGrid
                rows={followups}
                columns={columns}
                pageSize={15}
                checkboxSelection
              />
            </div>
          </div>
        ) : (
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center'
            }}
          >
            <Typography>No followup</Typography>
          </div>
        )}
      </fieldset>
    </div>
  )
}
```

When I use the `valueGetter` property inside the items of `columns`, it shows the following error:

- on Edge 90:

  ```
  RangeError
  Maximum call stack size exceeded
  ```

- on Firefox 88:
  ```
  InternalError
  too much recursion
  ```

The grid renders all right and no error is shown when I remove all the `valueGetter` properties.

## Expected Behavior 🤔

The grid should render all right, with the dates properly formatted.

## Steps to Reproduce 🕹

Link to the CodeSandbox: https://codesandbox.io/s/festive-grothendieck-fk0lv?file=/src/Demo.tsx

I am using the component in a Next.js app, but the error also appears when the component is used in a CRA template.

Steps:

1. Add the packages `@material-ui/data-grid`, `date-fns` and `date-fns-tz`
2. Add the models `Client` and `Followup`
3. Add some dummy data of `Client` and `Followup`
4. Pass the data on to the component defined above

## Context 🔦

I am developing a front-end project using Next.js and Material-UI.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

  I am using Firefox 88.0 as my primary browser. The error also appears on Edge browser, as mentioned before.

```
System:
  OS: Windows 10 10.0.19041
Binaries:
  Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 7.11.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: Not Found
  Edge: Spartan (44.19041.906.0), Chromium (90.0.818.51)
npmPackages:
  @emotion/react: ^11.1.5 => 11.1.5
  @emotion/styled:  10.0.27
  @material-ui/core: ^4.11.3 => 4.11.3
  @material-ui/data-grid: ^4.0.0-alpha.26 => 4.0.0-alpha.26
  @material-ui/icons: ^4.11.2 => 4.11.2
  @material-ui/pickers: ^3.3.10 => 3.3.10
  @material-ui/styles:  4.11.3
  @material-ui/system:  4.11.3
  @material-ui/types:  5.1.0
  @material-ui/utils:  4.11.2
  @types/react: ^17.0.1 => 17.0.3
  react: ^17.0.1 => 17.0.2
  react-dom: ^17.0.1 => 17.0.2
  typescript: ^4.1.3 => 4.2.4
```

</details>

**Comment by dtassone** [comment]
You should use `valueFormatter` instead of `valueGetter` to format a date, as you are not getting a value that is not the current column value.

Also you should use `useState` for the columns as the grid uses immutability.

so this should work
```tsx
      valueFormatter: ({value})=> `${formatter('createdOn', value)}`
```

Lastly, FYI we also have a native `date` and `dateTime` column type that can do manage date columns for you, so you will get sorting and filtering, and if you need another format just override the `valueFormatter` property

https://material-ui.com/components/data-grid/columns/#column-types

**Comment by dtassone** [comment]
that being said, we have an issue with `getValue` when calling it from with the field of its definition.
ie
```tsx
const column = {field: 'name', getValue: ({getValue})=> getValue('name')} 
```
This results in max call stack error.

That will be fixed with #1513

**Comment by oliviertassinari** [comment]
> That will be fixed with #1513

@dtassone What's the solution? It looks like getValue calls getValue 😆.

**Comment by dtassone** [comment]
Closing as this is fixed in #1513

**Comment by oliviertassinari** [comment]
It's not fixed. I have updated the reproduction to use the latest version.

**Comment by venik2007** [comment]
On DataGrid V5 this issue still exist, I found a reason of recursion - if happens if `field` equals to `getValue field` 
[Codesandbox example](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-pq57l?file=/src/App.tsx): 

Works:
```
field: "col1_REMOVE_ME_",
valueGetter: (params) => params.getValue(params.id, "col1"),
```
Recursion:
```
field: "col1",
valueGetter: (params) => params.getValue(params.id, "col1"),
```
