### ISSUE TITLE
[DataGrid] Column header is moving when keyboard arrow keys are pressed

### ISSUE THREAD

**Issue by Deligar** [mui-org/material-ui-x#2103]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When all columns have property flex the header is moving when keyboard arrow keys are pressed (header doesn't match columns after moving)

Before:
![image](https://user-images.githubusercontent.com/65401960/124922789-86241480-e002-11eb-8f6c-914c4071113d.png)

After:
![image](https://user-images.githubusercontent.com/65401960/124922936-a653d380-e002-11eb-8422-cddc395ba028.png)

## Expected Behavior 🤔

Header should remain still

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/columns/#fluid-width
2. Click on the first cell
3. Press right arrow key on the keyboard
4. Header sould move to the left
5. Press left arrow key on the keyboard
6. Header should go back in place

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

Browser: Google Chrome v91.0.4472.124

**Comment by flaviendelangle** [comment]
I reproduct your behavior on the published documentation.

And on the master branch I have a different behavior (but also not great).
https://user-images.githubusercontent.com/3309670/124929373-bc609480-e000-11eb-9f75-f05fa392a71e.mp4

Same thing on this PR : https://deploy-preview-2084--material-ui-x.netlify.app/components/data-grid/columns/#fluid-width

**Comment by flaviendelangle** [comment]
Relates to #2011

**Comment by m4theushw** [comment]
This bug also happens when all columns are not using fluid widths . The problem is that `isColumnVisibleInWindow` is returning false when the column to scroll is the last one and it ends at the very end of the viewport, leaving no space after it. In #1964 we improved this logic to consider the column width, but it seems that we missed the column-to-scroll-is-at-the-very-end scenario. If we look at the latest release, the bug is worse because it moves just by navigating to the second column. With #1964 it only moves when navigating to the last column.

https://github.com/mui-org/material-ui-x/blob/b5380b9a227187f4640f00cf223532e3e34561c1/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts#L196

I suppose the fix envolves improving the logic below, because the `lastColIndex` returned in this case is from the 2nd column, when it should be from the 3rd column.

https://github.com/mui-org/material-ui-x/blob/b5380b9a227187f4640f00cf223532e3e34561c1/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts#L90-L94

Space after the last column = no movement

<img width="600" src="https://user-images.githubusercontent.com/42154031/124978740-8c1cf400-e008-11eb-98da-da874a580c99.gif" alt="A7hpGvr2tX" style="max-width:100%;">

Little to no space after the last column (fluid width) = moves a bit to the left

<img width="600" src="https://user-images.githubusercontent.com/42154031/124978905-bec6ec80-e008-11eb-80de-d43f0102c042.gif" alt="k9rZwCiRRb" style="max-width:100%;">

**Comment by oliviertassinari** [comment]
@m4theushw Regarding `isColumnVisibleInWindow`, I don't think that we should spend more time improving it. We can remove it, remove half of the logic to handle vertical positioning, reproducing the one we use to handle horizontal one, without bugs.

**Comment by m4theushw** [comment]
@oliviertassinari I think you inverted between "vertical" and "horizontal". I don't think we can remove it. In the y-axis, the row height is fixed (at least now) while it can vary in the x-axis. The logic requires more complexity. We could remove it from the API and bring it to the same hook that deals with the vertical scrolling.

**Comment by dtassone** [comment]
This issue comes from a negative margin on the separator, I have fixed it in #2110

**Comment by oliviertassinari** [comment]
Having a closer look I didn't solve this in #2162. It can still be reproduced in https://material-ui.com/components/data-grid/#mit-version.

**Comment by oliviertassinari** [comment]
I have spent 5 minutes looking at this, it seems that we forgot to clean up when we changed the sync logic between the header and the body.

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
index 419bad70..c373ba00 100644
--- a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
+++ b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
@@ -288,8 +288,7 @@ export const useGridVirtualRows = (apiRef: GridApiRef): void => {

   const scroll = React.useCallback(
     (params: Partial<GridScrollParams>) => {
-      if (windowRef.current && params.left != null && colRef.current) {
-        colRef.current.scrollLeft = params.left;
+      if (windowRef.current && params.left != null) {
         windowRef.current.scrollLeft = params.left;
         logger.debug(`Scrolling left: ${params.left}`);
       }
@@ -299,7 +298,7 @@ export const useGridVirtualRows = (apiRef: GridApiRef): void => {
       }
       logger.debug(`Scrolling, updating container, and viewport`);
     },
-    [windowRef, colRef, logger],
+    [windowRef, logger],
   );

   const getScrollPosition = React.useCallback(
```
