### ISSUE TITLE
[DataGrid] "Cannot read property 'id' of undefined" when rows updates

### ISSUE THREAD

**Issue by BrentFarese** [mui-org/material-ui-x#571]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

We are utilizing the XGrid component.  We have a responsive layout whereby we hide columns in the XGrid if the layout becomes too small.  When we get to a breakpoint resizing the window and try to hide columns, XGrid breaks.  See GIF below.

![2020-11-11 16 20 08](https://user-images.githubusercontent.com/25846953/98866179-8c91ca80-243a-11eb-90a7-772319804f87.gif)

These are the errors we see in the console:

![Screen Shot 2020-11-11 at 4 27 03 PM](https://user-images.githubusercontent.com/25846953/98866373-d2e72980-243a-11eb-8bd2-143e1e6bd0ca.png)

![Screen Shot 2020-11-11 at 4 26 43 PM](https://user-images.githubusercontent.com/25846953/98866382-d4b0ed00-243a-11eb-9a24-5703e62db82b.png)

## Expected Behavior 🤔

Resizing of the browser window and hiding columns as a result should work as expected without error.

## Steps to Reproduce 🕹

Steps:

1.  Create XGrid with multiple columns.
2.  Hide some columns programmatically using a breakpoint (e.g., we use `useMediaQuery` hook from MUI and the `hide` prop of the `ColDef` to do this).
3.  Should see the XGrid error out after 2.

I can confirm that removing the `hide` prop from our `ColDef`s causes the error to go away.

## Context 🔦

Trying to make the XGrid responsive to layout changes in our app.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.9  |
| Material-UI | v4.10.2 |
| React         |    17     |
| Browser       |    Chrome     |
| TypeScript    |    Y    |

**Comment by oliviertassinari** [comment]
Do you have a reproduction we can look at?

**Comment by BrentFarese** [comment]
> Do you have a reproduction we can look at?

@oliviertassinari here is a [Codesandbox link](https://codesandbox.io/s/material-ui-data-grid-bug-csdge?file=/src/App.tsx) with a (somewhat) reproduction.  Comment out the `useMediaQuery` hook and the `hide` props and you can see a failure occurs.  However, it is a different failure than I experienced in our setup.  But, perhaps the reproduction sheds light on the issue.

Let me know if you need more.  Thanks!

**Comment by oliviertassinari** [comment]
@BrentFarese Thanks for the reproduction. I don't think that it's the same problem. I'm renaming the issue. This is a simplified version: https://codesandbox.io/s/material-ui-data-grid-bug-forked-b9g0g?file=/src/App.tsx.

**Comment by BrentFarese** [comment]
> @BrentFarese Thanks for the reproduction. I don't think that it's the same problem. I'm renaming the issue. This is a simplified version of the bug: https://codesandbox.io/s/material-ui-data-grid-bug-forked-b9g0g?file=/src/App.tsx.
> 
> Your reproduction works if you [make the rows stable](https://codesandbox.io/s/material-ui-data-grid-bug-forked-6tn2g?file=/src/App.tsx). The data grid doesn't use `useDebugValue`, as far as I know, so you would need search somewhere else.

Thank you for looking into it @oliviertassinari.  I can confim that extracting the row data out/making the rows stable does seem to work.  But that doesn't seem viable in production as our row data is dynamic.  I can also confirm that removing the `hide` props in `ColDefs` gets rid of the error.

I'm not sure if it's related to our issue.  I think it **_might_** be.  Both stack traces seem to lead to the `ViewPort` component in `DataGrid` (for us`XGrid`).  Maybe that is where the root issue lies?

I have tried to fiddle more with my reproduction to get it to reproduce the exact error we are seeing in the GIF/screenshots above, but it's difficult.  I will post an update here if I can reproduce the exact error.

Thanks!

**Comment by shyam-vijayakumar** [comment]
Not sure if this is the same issue, but it seems like it. I'm trying to do something more basic though, just updating the rows based on a button click. Am I missing something here or is this a reproduction of this bug?

https://codesandbox.io/s/clever-ptolemy-zjn6h

Thanks.

**Comment by ryanrogalski** [comment]
+1 for this issue, I am experiencing the same error when trying to re-render an `XGrid` or `DataGrid` component by updating the `rows` prop when an array of data changes. I can fix the error by making the rows data stable, but our row data is dynamic as well so this is not a viable solution.

**Comment by oliviertassinari** [comment]
My reproduction is fixed (https://codesandbox.io/s/material-ui-data-grid-bug-forked-b9g0g?file=/package.json) with #599.

**Comment by oliviertassinari** [comment]
The fix was released in v4.0.0-alpha.10.

**Comment by vitalist82** [comment]
In version 4.0.0-alpha.32 I still get the error after I update the rows property with a new set of rows where one row was removed. 

My scenario is:

1. deleting the row from the data source (e.g. on onRowClick)
2. fetching the updated data from source (with one row deleted obviously)
3. providing the updated row set to the XGrid (this happens without an error for the first time)
4. clicking on another row in the updated table

I think it is quite typical scenario to want to be able to delete rows from the table or add new ones, so I'm wondering whether this is still an issue in XGrid or it might be just a wrong usage from my side.

**Comment by oliviertassinari** [comment]
@vitalist82 If you have a minimal reproduction with the latest version, please open a new issue. You can find a codesandbox template in the new issue template.

**Comment by vitalist82** [comment]
@oliviertassinari i opened a new issue #1958 with a codesandbox.

**Comment by twigs67** [comment]
Ya, still getting this error on `^4.0.0-alpha.33`
